# Generated by Django 5.2 on 2025-08-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent', models.CharField(max_length=255, unique=True, verbose_name='Id_Stripe')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('currency', models.CharField(default='MXN', max_length=10, verbose_name='Divisa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
