# Generated by Django 5.2 on 2025-08-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Id_Stripe'),
        ),
    ]
