# Generated by Django 5.2 on 2025-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('requires_action', 'Requiere intervención')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
