# Generated by Django 5.2 on 2025-08-20 10:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_refund_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de reembolsos'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(choices=[('none', 'Nulo'), ('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='none', max_length=20, verbose_name='Estado del reembolso'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto a devolver'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id del reembolso'),
        ),
    ]
