# Generated by Django 5.2 on 2025-08-21 11:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_last_refund_at_payment_refund_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='last_refund_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de último reembolso'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Anticipo'), ('balance', 'Saldo'), ('cancellation_fee', 'Penalización por cancelación'), ('no_show', 'Penalización por no aparecer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Razón de reembolso'),
        ),
        migrations.CreateModel(
            name='RefundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(max_length=255, unique=True, verbose_name='Id del Reembolso')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cantidad a reembolsar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_logs', to='payments.payment', verbose_name='Pago asociado')),
            ],
            options={
                'indexes': [models.Index(fields=['payment'], name='payments_re_payment_d7ef5d_idx')],
            },
        ),
    ]
