# Generated by Django 5.2 on 2025-08-25 11:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_last_refund_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundlog',
            options={'verbose_name': 'Registro de reembolso', 'verbose_name_plural': 'Registro de reembolsos'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Anticipo'), ('balance', 'Saldo'), ('cancellation_fee', 'Penalización por cancelación'), ('no_show', 'Penalización por no aparecer')], max_length=20, verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto devuelto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id sesión de stripe'),
        ),
        migrations.AlterField(
            model_name='refundlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto reembolsado'),
        ),
    ]
