# Generated by Django 5.2 on 2025-08-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_refundlog_options_alter_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_reference_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id referencia del cliente'),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración'),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave de idempotencia'),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos'),
        ),
        migrations.AddField(
            model_name='payment',
            name='superseted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reemplazo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('requires_action', 'Requiere intervención'), ('void', 'Anulado'), ('superseded', 'Reemplazado'), ('expired', 'Caducado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
