# Generated by Django 5.2 on 2025-08-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_client_reference_id_payment_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='superseted_at',
            new_name='superseded_at',
        ),
    ]
