# Generated by Django 5.2 on 2025-12-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_booking_avail_idx_booking_booking_user_idx_and_more'),
        ('payments', '0010_rename_superseted_at_payment_superseded_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'payment_type', 'status'], name='payment_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payment_stripe_pi_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_checkout_session_id'], name='payment_stripe_cs_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'expires_at'], name='payment_expires_idx'),
        ),
    ]
