# Generated by Django 5.2 on 2026-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_payment_payment_lookup_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Anticipo'), ('balance', 'Saldo'), ('extension', 'Extensión de estancia'), ('cancellation_fee', 'Penalización por cancelación'), ('no_show', 'Penalización por no aparecer')], max_length=20, verbose_name='Tipo de pago'),
        ),
    ]
