# Generated by Django 5.2 on 2025-09-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('beds', models.CharField(default='Cama matrimonial', max_length=200, verbose_name='Número de camas')),
                ('max_people', models.IntegerField(verbose_name='Capacidad')),
                ('nightly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Noche')),
                ('address', models.CharField(max_length=200, verbose_name='Localización')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Altitud')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties', verbose_name='Imagen')),
                ('cover', models.BooleanField(db_index=True, default=False, verbose_name='Portada')),
                ('position', models.PositiveIntegerField(default=0, help_text='Orden en la galería')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['property', 'cover'], name='properties__propert_1da8b8_idx')],
            },
        ),
    ]
