# Generated by Django 5.2 on 2025-10-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='airbnb_ical_url',
            field=models.URLField(blank=True, null=True, verbose_name='Calendario iCal de Airbnb'),
        ),
    ]
