# Generated by Django 5.2 on 2025-12-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_airbnb_ical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ical_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
