# Generated by Django 5.2 on 2025-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_nightly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mensual'),
        ),
        migrations.AddField(
            model_name='property',
            name='weekly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio semanal'),
        ),
    ]
