# Generated by Django 5.2 on 2025-08-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_monthly_price_property_weekly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='weekly_price',
        ),
    ]
