# Generated by Django 5.2 on 2025-08-10 11:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='banlance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Balance'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Depósito'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_consumer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id_cliente_stripe'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto total'),
        ),
    ]
