# Generated by Django 5.2 on 2025-08-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_banlance_due_booking_deposit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='banlance_due',
            new_name='balance_due',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='stripe_consumer_id',
            new_name='stripe_customer_id',
        ),
    ]
