# Generated by Django 5.2 on 2025-08-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_banlance_due_booking_balance_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
