# Generated by Django 5.2 on 2025-08-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_hold_expires_at_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id cliente stripe'),
        ),
    ]
