# Generated by Django 5.2 on 2025-08-25 11:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_stripe_customer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_arrival', models.DateTimeField(verbose_name='Llegada antigua')),
                ('new_arrival', models.DateTimeField(verbose_name='Llegada nueva')),
                ('old_departure', models.DateTimeField(verbose_name='Salida antigua')),
                ('new_departure', models.DateTimeField(verbose_name='Salida nueva')),
                ('old_T', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Antiguo total')),
                ('new_T', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nuevo total')),
                ('deposit_topup', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Depósito extra')),
                ('deposit_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Devolución')),
                ('old_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Balance antiguo')),
                ('new_balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Nuevo balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.booking', verbose_name='Reserva modificada')),
            ],
            options={
                'verbose_name': 'Registro de cambio de reservas',
                'verbose_name_plural': 'Registros de cambio de reservas',
            },
        ),
    ]
