# Generated by Django 5.2 on 2025-08-26 10:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchangelog',
            name='paid_dep',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Depósito pagado'),
        ),
    ]
