# Generated by Django 5.2 on 2025-08-26 11:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingchangelog_paid_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchangelog',
            name='deposit_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Nuevo depósito'),
        ),
        migrations.AlterField(
            model_name='bookingchangelog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='bookings.booking', verbose_name='Reserva modificada'),
        ),
    ]
