# Generated by Django 5.2 on 2025-08-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingchangelog_deposit_target_and_more'),
        ('payments', '0010_rename_superseted_at_payment_superseded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchangelog',
            name='checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Checkout ID (Stripe)'),
        ),
        migrations.AddField(
            model_name='bookingchangelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('applied', 'Aplicado'), ('superseded', 'Reemplazado')], default='pending', max_length=60, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='bookingchangelog',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingchangelog',
            name='topup_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='payments.payment', verbose_name='Pago top up '),
        ),
    ]
