# Generated by Django 5.2 on 2025-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookingchangelog_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='balance_charge_eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha para cobro automático de balance'),
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_charge_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificador de la tarea'),
        ),
    ]
