# Generated by Django 5.2 on 2025-12-08 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_user'),
        ('properties', '0003_property_ical_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'status', 'arrival', 'departure'], name='booking_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='booking_user_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'hold_expires_at'], name='booking_hold_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['arrival', 'departure'], name='booking_dates_idx'),
        ),
    ]
