# Generated by Django 5.2 on 2026-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_booking_avail_idx_booking_booking_user_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('expired', 'Expirada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
